# Generated by Django 4.2.4 on 2023-11-25 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Productos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("descripcion", models.CharField(max_length=50)),
                ("precio", models.CharField(max_length=10)),
                (
                    "categorias",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestorProducts.categorias",
                    ),
                ),
            ],
        ),
    ]
